version: '3.8'
services:
  api:
    build: ./app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:////code/app.db
      - REDIS_URL=redis://redis:6379/0
      - GENAI_API_KEY=${GENAI_API_KEY}
    volumes:
      - ./app.db:/code/app.db
      - ./uploads:/code/uploads
    depends_on:
      - redis
    networks:
      sda-network:
        ipv4_address: 172.28.0.2
  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"
    networks:
      sda-network:
        ipv4_address: 172.28.0.3

networks:
  sda-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16
